[package]
name = "rupervise"
version = "0.1.0"
authors = ["Greg Kent <gregokent@gmail.com>"]

[dependencies]
libc = "0.2.16"
rustbox = "0.9.0"
regex = "0.1.77"
lazy_static = "*"

[dependencies.xi-rpc]
path = "rpc"
